eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname:  localhost
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capability-customer?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  

capability:
  microservice: 
    localization: capability-chicken
    secure: false